version: '3.9'

services:
  namenode:
    image: hadoop_base:1
    container_name: namenode
    hostname: namenode
    ports:
      - "9000:9000"  # RPC NameNode
      - "9870:9870"  # Web UI NameNode
    volumes:
      - namenode_data:/opt/hdfs/namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  datanode1:
    image: hadoop_base:1
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1_data:/opt/hdfs/datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  datanode2:
    image: hadoop_base:1
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2_data:/opt/hdfs/datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  datanode3:
    image: hadoop_base:1
    container_name: datanode3
    hostname: datanode3
    volumes:
      - datanode3_data:/opt/hdfs/datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
  datanode3_data:
