version: '3'
services:
  namenode:
    image: custom-hadoop-namenode  
    environment:
      - CLUSTER_NAME=hadoop_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/opt/hadoop_tmp/hdfs/namenode

  datanode1:
    image: custom-hadoop-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode1_data:/opt/hadoop_tmp/hdfs/datanode
    depends_on:
      - namenode

  resourcemanager:
    image: custom-hadoop-namenode
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    ports:
      - "8088:8088"  # Cổng Web UI của ResourceManager
    depends_on:
      - namenode

  nodemanager1:
    image: custom-hadoop-namenode
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    depends_on:
      - resourcemanager

  nodemanager2:
    image: custom-hadoop-namenode
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    depends_on:
      - resourcemanager

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
